### ISSUE TITLE
Scale factor

### ISSUE THREAD

**Issue by mnordseth** [toreamun/amshan-homeassistant#1]
Thanks for a great plugin, this is by far the cleanest AMS HAN solution I have looked at.

In my home, the Energy Meter (a Aidon 6540) is not connected directly to main power, but through a current transformer with a reduction factor of 50. I believe this setup is common when you have a large main fuse (in my case 125A). 

The data output of the HAN port is also reduced by a factor of 50.

Is it possible to add a config variable for scaling the data that is read, this has to be done for all currents, power and energy measurements?

Thanks,
Magnus

**Comment by toreamun** [comment]
I am glad you like it.

I'll look into it.

Do you have a litt bit more context about an installation using a current transformer? I cannot remember to have seen anything about this in the official HAN documentation. Maybe the scale factor is somewhere in the data stream and can be used automatically.

Thanks for the feedback.

Tore

**Comment by mnordseth** [comment]
Sure, it would be great if it is in the data, but I suspect it isn't. I think the meter itself is unaware of the fact that the current is measured indirectly, and that the net provider only has this information in their backend system. I will ask my provider about it.

When I look at the energy consumption on the display of the meter, it is also off by a factor 50.

I found a document [https://docplayer.me/295393-Retningslinjer-og-krav-for-malermontasje-og-kontroll-av-malepunktet-tilhorende-eidsiva-nett-as.html](url) that describes the electrical principle and regulations around this, turns out it is done when the main fuse is 80A or larger. 

Thanks for looking into it.

**Comment by toreamun** [comment]
Please also ask your provider exactly what values in the HAM feed should be scaled to be sure I do it correctly.

**Comment by mnordseth** [comment]
I just got feedback from Hafslund, that the meter is unaware about the scaling factor. It is applied in their backend systems for billing, etc. Hence, it is not possible to read this from the HAN port.

**Comment by toreamun** [comment]
Do you known if exports and reactive power also should be scaled?

See  Active power - (Q2+Q3), Reactive power + (Q1+Q2), Reactive power - (Q3+Q4), Cumulative hourly active export energy (A-) (Q2+Q3), Cumulative hourly reactive import energy (R+) (Q1+Q2) and Cumulative hourly reactive export energy (R-) (Q3+Q4) on page 6: https://www.nek.no/wp-content/uploads/2018/11/Aidon-HAN-Interface-Description-v10A-ID-34331.pdf

**Comment by mnordseth** [comment]
Yes they should be.

**Comment by toreamun** [comment]
This should now be resolved 0.2.2 pre-release. Currents, power and energy measurements are now multiplied by scale factor 1 by default. This can be configured in options.

You have a transformer reduction factor of 50. Do this mean that this new scale factor in you case should 50?

You may have to select reinstall and enable beta versions for the integration in HACS to see the pre-release as an install option.

Please give feedback if this solves the issue when you have tested the pre-release.

**Comment by toreamun** [comment]
@mnordseth Have you had the chance to check if the pre-release solves your problem?

**Comment by mnordseth** [comment]
Thanks a lot, this seems to solve my issue!
