### ISSUE TITLE
Amper vises feil etter oppdatering av HA til v2021.6.x

### ISSUE THREAD

**Issue by ghost** [toreamun/amshan-homeassistant#2]
Etter oppdatering av HA til v2021.6.x, så vises Amp-verdiene feil.. De har ikke noe samsvar med Watt.
Watt er derimot tilsynelatende korrekt da det ikke har vært noen avvik fra tidligere historikk.
![image](https://user-images.githubusercontent.com/1651061/121502982-f0846d80-c9e0-11eb-9409-5c96ae7efc13.png)

**Comment by toreamun** [comment]
Det var pussig. Viser den feil hele tiden etter, eller bare i perioder? Hva er verdien av Aidon OBIS List version identifier?

Jeg ser du også har en negativ strøm. Produserer du selv strøm?

Legg også merke til at verdiene for strøm og spenning ikke sendes fra måler like ofte som effektforbruk, og disse verdiene kan derfor være litt "ute av synk" i forhold til hverandre. Ca hvert 10 sekund er alle verdiene fra samme målerdatamelding.

**Comment by slippern** [comment]
Det virker i grunn som at den henger seg på noe vis..
Fase L1 står fremdeles med 2,4A og L3 med -1.0 i skrivende stund.
Også historikken viser dette.
At Amperen går over 10A er også helt usannsynlig,
![image](https://user-images.githubusercontent.com/1651061/121511544-0a29b300-c9e9-11eb-92ac-63b7732aea15.png)
![image](https://user-images.githubusercontent.com/1651061/121511686-32191680-c9e9-11eb-9c1c-0f3ed378297f.png)
![image](https://user-images.githubusercontent.com/1651061/121511766-4bba5e00-c9e9-11eb-8445-b7c2a10a0600.png)

Effektforbruket er maks oppe i 6kW på en god dag... 

Ang negativ strøm, så produserer jeg ikke noe strøm selv, så dataene er rape gal med unntak av faktisk effektforbruk.

Veriden av OBIS List Version er: AIDON_V0001

**Comment by toreamun** [comment]
Det blir ikke foretatt noen substraksjon på verdiene som kommer direkte fra måler. Kun skalering i noen tilfeller, og skalering vil ikke kunne gi en negativ verdi.

I følge Glitre sin håndbok for Aidon, så "finnes flere grunner til at en måler indikerer negativ strøm". Det kan blant annet være tilkoblingen av målersløyfene. Slik jeg forstår det, så skal negativ strøm vises på displayet på selve måleren. Se 5.3.2.3 i [Håndbok for arbeid i målepunkt](https://www.glitreenergi-nett.no/wp-content/uploads/2020/09/Handbok-for-arbeid-i-malepunkt-14-007-1876137-1-1-1.pdf).

Jeg har selv en Aidon, og har ingen negative målinger (har sjekket målinger tilbake til mars 2021).

**Comment by toreamun** [comment]
Ingen tilbakemelding. Feilen kan være knyttet til måleren.
