### ISSUE TITLE
Verdier som sendes fra måler akkumulert hver time bør lagres

### ISSUE THREAD

**Issue by toreamun** [toreamun/amshan-homeassistant#21]
Verdier som sendes fra måler akkumulert hver time bør lagres slik at de kan benyttes med omstart uten å måtte vente inntil 1 time på ny måling. Når verdiene hentes frem ved oppstart må det sjekkes at verdiene ikke er foreldet før de kan benyttes. 

Følgende sendes kun hver time:
- Cumulative hourly active import energy (A+) (Q1+Q4)
- Cumulative hourly active export energy (A-)( Q2+Q3)
- Cumulative hourly reactive import energy (R+) ( Q1+Q2)
- Cumulative hourly reactive export energy (R-) (Q3+Q4)

**Comment by erlend-aasland** [comment]
Det manglar eit adverb her 😉 

```diff
-Når verdiene hentes frem ved oppstart må det sjekkes at verdiene er foreldet før de kan benyttes.
+Når verdiene hentes frem ved oppstart må det sjekkes at verdiene ikke er foreldet før de kan benyttes.
```

Tenkjer du at "forelda" er alt over 1 time?

**Comment by toreamun** [comment]
Jeg hadde tenkt å forsøke meg på noe så enkelt som under en timer og fra samme time på døgnet som inneværende. De tre målermerkene som er i markedet akkumulerer hver hele time, og sender dem 10 sekunder etter dette hvis jeg forstår dokumentasonen riktig (stemmer også bra med min erfaring).

**Comment by toreamun** [comment]
Implementert i utgivelse https://github.com/toreamun/amshan-homeassistant/releases/tag/2022.1.2
