### ISSUE TITLE
Støtte for svenske AMS målere

### ISSUE THREAD

**Issue by toreamun** [toreamun/amshan-homeassistant#24]
Sverige er i ferd med å fase inn AMS-målere. Energiföretagen har laget [Branschrekommendation för lokalt kundgränssnitt för elmätare](https://www.energiforetagen.se/globalassets/energiforetagen/det-erbjuder-vi/kurser-och-konferenser/elnat/branschrekommendation-lokalt-granssnitt-v2_0-201912.pdf).

Aidon sin spesifikasjon er [publisert](https://www.tekniskaverken.se/siteassets/tekniska-verken/elnat/aidonfd-rj12-han-interface-sv-v15d.pdf).

[Tibber Pulse](https://support.tibber.com/sv/articles/4559750-tibber-pulse-han-specifikationer) har støtte for flere svenske målere. Spesifikasjonen for Aidon er tilgjengelig. Det hadde vært veldig nyttig å få tak i spesifikasjonen for Kaifa/Nuri, Kamstrup, Landis+Gyr/Embriq og eventuelle andre svenske målere.

Hjelpe til testing og testdata fra noen med svensk måler hadde også vært veldig nyttig. Det er også nødvendig med en svenskspråklig som kan oversette https://github.com/toreamun/amshan-homeassistant/blob/master/custom_components/amshan/translations/en.json

**Comment by erlend-aasland** [comment]
Kanskje lurt å lufte det på HA sin Discourse-server?

**Comment by koppelo** [comment]
Här är data från Landis+Gyr E360.
Använder Tibber Pulse + MQTT.

esphome-p1reader har stöd för L+G E360.
Det går att utläsa protokollet från deras källkod.

[https://github.com/psvanstrom/esphome-p1reader/blob/main/p1reader.h](https://github.com/psvanstrom/esphome-p1reader/blob/main/p1reader.h)
[home-assistant.log](https://github.com/toreamun/amshan-homeassistant/files/8000855/home-assistant.log)

**Comment by toreamun** [comment]
Takk. Jeg tror jeg begynner å få kontroll på protokollen, men jeg trenger litt testdata for å verifisere. 

Har du mulighet til å hente litt testdata direkte fra ditt MQTT topic? Hvis du kjører MQTT integrasjonen i Home Assistant, så kan du gå til integrasjonen og velge configure. Deretter legger du inn ditt topic under "Listen to a topic", som da vil dumpe ut det Pulse publiserer:
![image](https://user-images.githubusercontent.com/12134766/152508608-ba7c23d3-f389-409a-b1cb-25815cee4e33.png)

Alternativt kan du f.eke benytte mosquitto_sub om du kjører mac/linux:
`mosquitto_sub -h YOURIPADDRESS -t 'YOUR_TIBBER_TOPIC'
`

Om du ikke ønsker å legge ut dine data public kan du sende dem til tore@amundsen.org

**Comment by koppelo** [comment]
Tack själv @toreamun

Duger detta?

`mosquitto_sub -t tibber > mqtt.log`
[mqtt.log](https://github.com/toreamun/amshan-homeassistant/files/8001977/mqtt.log)

**Comment by toreamun** [comment]
Ja, dette er supert. Mange takk.

**Comment by toreamun** [comment]
@koppelo Har du mulighet til å se om https://github.com/toreamun/amshan-homeassistant/releases/tag/2022.2.2-beta fungerer for deg?

**Comment by skunkmailen** [comment]
Tack!
Det ser ut att fungera. :-)

![bild](https://user-images.githubusercontent.com/98615259/152708082-1f60b8ab-d387-478b-98a7-fdf154c31460.png)

**Comment by toreamun** [comment]
Hvilken type mätare har du @skunkmailen?

**Comment by koppelo** [comment]
@skunkmailen är jag.
Jag skrev från en annan dator, därav att det blev postat med fel konto.
