### ISSUE TITLE
Cannot setup with socat

### ISSUE THREAD

**Issue by roflmao** [toreamun/amshan-homeassistant#3]
## Version of the custom_component
amshan 2021.8.0
HA 2021.8.0

HW (/dev/ttyUSB0): https://www.aliexpress.com/item/32719562958.html?spm=a2g0s.9042311.0.0.c8314c4dpbv1pv

Add your logs here.

GUI configuration:
https://www.jottacloud.com/s/00643aade031e2a4226b56ba0c793a0c52c

Followed by:

```
2021-08-06 22:17:59 INFO (MainThread) [amshan.meter_connection[] SmartMeterFrameContentProtocol[3]: Smart meter connected to host 192.168.69.107 and port 1234
```

PS: no debug logs even with config:
```
logger:
  default: info
  logs:
    homeassistant.components.zwave_js: debug
    custom_components.amshan: debug
```

## Describe the bug
Am i using socat wrong?  Ive tried multiple combinations but the component fails to succeed.
```
root@rpi-zero:~# socat /dev/ttyUSB0,b57600,rawer TCP-LISTEN:1234,reuseaddr
2021/08/06 22:14:00 socat[20415] E write(7, 0x196b2a8, 1): Broken pipe
root@rpi-zero:~# socat /dev/ttyUSB0,b115200,raw TCP-LISTEN:1234,reuseaddr
2021/08/06 22:14:30 socat[20486] E write(7, 0x19562a8, 1): Broken pipe
root@rpi-zero:~# socat -d tcp-listen:1234,fork /dev/ttyUSB0,raw,echo=0,b115200
2021/08/06 22:16:30 socat[20653] E write(6, 0x4842f0, 1): Broken pipe
```

**Comment by roflmao** [comment]
Ok, so i got the socat done and component setup:
```
socat /dev/ttyUSB0,raw,echo=0 tcp-listen:8888,reuseaddr
```
Maybe put up this as an example for easier setup.

systemd example service:

```
[Unit]
Description=socat amshan usb

[Service]
Type=simple
ExecStart=/usr/bin/socat /dev/ttyUSB0,raw,echo=0 tcp-listen:8888,reuseaddr
Restart=always

[Install]
WantedBy=multi-user.target

**Comment by toreamun** [comment]
I wonder what the purpose is? You can connect the integration selecting serial or TCP.

**Comment by roflmao** [comment]
@toreamun The purpose of using socat is for connecting HA from one server to another raspberry pi with a usb MBUS to my HAN.
Still experiencing socat issues when setting up:

```
root@rpi-zero:~# /usr/bin/socat -d -d  /dev/ttyUSB0,raw,echo=0 tcp-listen:8888,reuseaddr
2021/08/07 21:22:40 socat[15264] N opening character device "/dev/ttyUSB0" for reading and writing
2021/08/07 21:22:40 socat[15264] N listening on AF=2 0.0.0.0:8888
2021/08/07 21:22:44 socat[15264] N accepting connection from AF=2 192.168.69.194:59514 on AF=2 192.168.69.107:8888
2021/08/07 21:22:44 socat[15264] N starting data transfer loop with FDs [5,5] and [7,7]
2021/08/07 21:22:56 socat[15264] N socket 2 (fd 7) is at EOF
2021/08/07 21:22:57 socat[15264] N exiting with status 0
```

This is when im hitting "Submit " in HA setup. Do you have another working example with socat?

**Comment by toreamun** [comment]
I use ser2net running on a PI connected to a USB MBUS device to do the same. 

Example /etc/ser2net.conf:
`
3001:raw:600:/dev/ttyUSB0:2400 8DATABITS EVEN 1STOPBIT
`

Then connect to your PI on port 3001 (in this example) directly from the Home Assistant integration setup.

**Comment by roflmao** [comment]
Tried ser2net without luck;
```
2021-08-07 22:15:45 INFO (MainThread) [amshan.meter_connection] SmartMeterFrameContentProtocol[0]: Smart meter connected to host 192.168.69.107 and port 3001
```

Nothing more with debug logging fails on setup with the "unknown error occured" in HA gui.

**Comment by toreamun** [comment]
I think ser2net close the connection immediately after connect if you are already connected to the port (like your telnet test). You may want to try to restart ser2net to reset any connections. The generic error message you got is used for all cases not specifically handled. More TCP/IP connection issues should have been handled... 
Look for more log messages following the connect message.
