### ISSUE TITLE
AmsToMqttBridge og MQTT

### ISSUE THREAD

**Issue by kardesken** [toreamun/amshan-homeassistant#33]
Jeg får ikke fullført konfigurasjonen AMSHAN. Den ender i timeout etter at jeg har lagt inn mqtt topic

Jeg bruker AmsToMqttBridge (samme som amsleser.no benytter seg av) og er på fw v2.1.1
Der benytter jeg meg av MQTT payload Raw data (bytes). 

Til info, så har jeg enfase, og ikke den mer normale tre fase inn i bo enheten min. Det kan om mulig endre litt på melding som blir sendt ut fra HAN porten?

Her er et utklipp av homeassistant loggen:
`2022-04-18 14:28:02 DEBUG (MainThread) [custom_components.amshan.metercon] Got payload without HDLC framing from topic power_ams: 37454130424132423231313345444141453645373030304630303030303030303043303745363034313230313044314330304646383030303030303231393041304534423631364437333734373237353730354635363330333033303331303930363031303130303030303546463041313033353337333033363335333633373332333733313335333333333332333033373039303630313031363030313031464630413132333633383336333133313331333134323445333233343332333133303331333033343330303930363031303130313037303046463036303030303031384330393036303130313032303730304646303630303030303030303039303630313031303330373030464630363030303030303030303930363031303130343037303046463036303030303030373230393036303130313146303730304646303630303030303044313030303030303030303930363031303132303037303046463132303045303030303030303030323331413745`

**Comment by toreamun** [comment]
Når jeg dekoder denne får jeg en tekst som er en lang hex:
`7EA0BA2B2113EDAAE6E7000F000000000C07E60412010D1C00FF80000002190A0E4B616D73747275705F563030303109060101000005FF0A103537303635363732373135333332303709060101600101FF0A1236383631313131424E32343231303130343009060101010700FF060000018C09060101020700FF060000000009060101030700FF060000000009060101040700FF0600000072090601011F0700FF06000000D10000000009060101200700FF1200E000000000231A7E
`

Hvis man igjen dekoder den teksten fra hex til binære data, så får man de binære data slik de er sendt fra måleren. Hvorfor man her har valgt å gjøre om fra binære data til hex-tekst før data publiseres til MQTT vet jeg ikke (MQTT fungerer helt fint med binære data). Jeg skal finne en løsning på dette.

**Comment by kardesken** [comment]
Den er god.

Er det da mer fornuftig at jeg går til [https://github.com/gskjold/AmsToMqttBridge](url) og spør om at rå data'en kan sendes ut som binære data istadenfor hex? 
Jeg kan ikke noe om programmering selv, så jeg vet ikke hva som er fornuftig her. Men da er det jo i allefall ikke noe feil med din HA addon.

Dette er jo ikke viktig i den forstand. Men da det ser ut som om din integrasjon også har en "minne" funksjon slik at dataen vises etter en restart, så tenkte jeg at jeg skulle prøve denne ut. Så lenge jeg bare bruker MQTT'en fra AmsToMqttBridge, så får jeg ofte en times opphold etter at jeg har restartet HA.

**Comment by toreamun** [comment]
Jeg åpnet en sak https://github.com/gskjold/AmsToMqttBridge/issues/210 og spurte om dataene kunne sendes ut som rådata slik de kommer fra måleren. Den ble akseptert og løst. Hvis det er slik at data først encodes som en hex string, så var det ikke helt det jeg ønsket meg. Jeg har dessverre ikke en Amsleser, så jeg får ikke testet. Jeg skal se om jeg ikke kan finne en løsning hvor jeg sjekker om data er en lang hex-string. Men det enkleste hadde jo vært om dataene bare kunne sendes som de kommer fra måleren uten å kodes om.

**Comment by toreamun** [comment]
https://github.com/toreamun/amshan-homeassistant/releases/tag/2022.4.0

**Comment by toreamun** [comment]
@kardesken Funker siste release for deg nå?

**Comment by kardesken** [comment]
Da har jeg akkurat oppdatert og nå klarer jeg å fullføre integrasjonen.
Så ja, det fungerer 👍 

Tusen takk for hjelpen
