### ISSUE TITLE
Timeout when trying to read from Kamstrup via MQTT (amsleser, k-pow)

### ISSUE THREAD

**Issue by fribse** [toreamun/amshan-homeassistant#34]
## Version of the custom_component
2022.4.0

## Configuration

The MQTT data looks like this
`
{"id":"xx","name":"amsleser","up":7059,"t":1650649460,"vcc":3.309,"rssi":-75,"temp":-127.00,"data":{"lv":"","id":"","type":"","P":1091,"Q":0,"PO":0,"QO":423,"I1":0.37,"I2":3.97,"I3":1.32,"U1":230.00,"U2":233.00,"U3":234.00,"PF":0.93,"PF1":0.83,"PF2":0.92,"PF3":0.97,"tPI":27086.02,"tPO":0.00,"tQI":20.90,"tQO":9414.54,"rtc":1650649460}}`

## Describe the bug
I have a K-Pow module with AMSLeser 2.1 on it, it delivers JSON data to MQTT.
When I try to use the amshan integration, I get a mesage that says timeout:

![billede](https://user-images.githubusercontent.com/13660621/164758365-2b8d4c0d-b2dc-4911-8d71-15bdc54f9bf6.png)

Is it not compatible?

## Debug log

```text
No logs

```

**Comment by toreamun** [comment]
The integration is compatible when Amsleser is configured to publish the data from the meter unparsed. I think the option in Amsleser is called "Raw data (bytes)".

**Comment by fribse** [comment]
Hi @toreamun 
Thankyou for getting back to me. The ams2mqtt has four different ways of posting to MQTT.
JSON
Raw (minimal)
Raw (Full)
Domoticz
I've tried both Raw (minimal) and Raw (Full) but it still just times out.

The raw minimal format as read by MQTT-Explorer:
![billede](https://user-images.githubusercontent.com/13660621/164885173-30d51f04-6202-4a3d-9a25-4860b398dae3.png)
The raw full format:
![billede](https://user-images.githubusercontent.com/13660621/164885216-24d34bca-7160-4b47-9253-5dd7d147ee2e.png)

I don't see anything in the log regarding this integration...

**Comment by fribse** [comment]
Problem solved, upgraded amstomqtt to 2.1.2, it has a home assistant format, and is now auto discovered in HA.
