### ISSUE TITLE
Tibber Pulse ikke tilgjengelig lenger.

### ISSUE THREAD

**Issue by perern** [toreamun/amshan-homeassistant#36]
Jeg får ikke kontakt med Pulse via Mosquitto lenger, verken med sertifikater, anonym login eller noe som helst.

MQTT conf:
acl_file /share/mosquitto/accesscontrollist
listener 1885
cafile /share/mosquitto/ca.crt
keyfile /share/mosquitto/client.key
certfile /share/mosquitto/client.crt
allow_anonymous true
require_certificate false
log_timestamp_format %Y-%m-%dT%H:%M:%S

MQTT tillater ikke lenger helt anonym pålogging og krever en form for innlogging, dette er mest trolig ikke mulig med Pulse siden den ikke har mulighet for å sende brukernavn og passord via webui og SSL ikke fungerer såvidt jeg kan se.

**Comment by toreamun** [comment]
Benytter du [Mosquitto broker Home Assistant Add-on](https://github.com/home-assistant/addons/blob/master/mosquitto/DOCS.md)?

Jeg ser at du benytter port 1885. Har du forsøkt med "standard" port 1883?

**Comment by perern** [comment]
> 

Bruker Mosquitto ja, jeg byttet port bare for å prøve. Kjører vanligvis 1883 feilfritt, prøvde 8883 med SSL og.

**Comment by tmjo** [comment]
Se tips [her ](https://www.hjemmeautomasjon.no/forums/topic/4255-tibber-pulse-mqtt/?page=4#comment-103100) om å bruke

`username:password@host`

i oppsettet til Pulse. Jeg satt akkurat opp min nå nettopp og slet med å få koblet til av samme årsak. Når jeg la inn brukernavn og passord på denne måten så koblet den seg fint til og begynte å rapportere data.

**Comment by perern** [comment]
> 

Dette virker, er aktiv i Home Assistant igjen. Helt uten Tibber abonnement.
