### ISSUE TITLE
MQTT feiler

### ISSUE THREAD

**Issue by knutmyr** [toreamun/amshan-homeassistant#39]
Etter problemer med leser og ny måler, får jeg ikke satt opp MQTT forbindelse. Virket før jeg fjernet integrasjonen, men etter å ha lagt den til på nytt, kommer det bare unknown error når jeg prøver legge den til. Har forsøkt flere versjoner. Mulig problemet ligger i HA, men finner ikke noe fornuftig i loggene. Bruker pow-u fra amsleser.no. Dette virket før måler ble skiftet. Noen tips hvor jeg skal begynne lete etter feil? Det kommer data til MQTT i HA når jeg lytter på emnet
```

**Comment by toreamun** [comment]
Det ser ut som jeg har vært litt rask med å tilpasse til endringer i HA. Release [2022.7.0](https://github.com/toreamun/amshan-homeassistant/releases/tag/2022.7.0) vil ikke fungere med HA < 2022.8.

Takk for at du rapporterte problemet.

**Comment by knutmyr** [comment]
Prøver på nytt i dag, men nå får jeg timeout reading data når jeg skal legge til integrasjonen. Får fortsatt riktig data når jeg lytter til emnet i mqtt integrasonen

**Comment by knutmyr** [comment]
Etter å ha ventet et par timer etter å ha installert siste versjon, fikk jeg lagt det inn igjen og det virker
