### ISSUE TITLE
Fetch Price

### ISSUE THREAD

**Issue by klem-everywhere** [toreamun/amshan-homeassistant#45]
I was looking at https://github.com/gskjold/AmsToMqttBridge and I see that prices are actually provided through AMS, can we have it in HA as well?

Thanks.

**Comment by toreamun** [comment]
This integration decodes messages in the native AMS format. A lot of differences sources is supported, and most of them don't provide prices. I don't want to bring in related features depending on other sources than the native AMS message. 

You can probably use a [MQTT sensor](https://www.home-assistant.io/integrations/sensor.mqtt/) to get the prices from  https://github.com/gskjold/AmsToMqttBridge

**Comment by klem-everywhere** [comment]
So I looked into it and apparently the prices from AmsToMqttBridge is from ENTSO-E.
I don't think AmsToMqttBridge should be the one fetch it from ENTSO-E.
