### ISSUE TITLE
sensor.kaifa_voltage_l2 Always showing 0 (zero"

### ISSUE THREAD

**Issue by Norwegiandroid** [toreamun/amshan-homeassistant#57]
When using Tibber Pulse and Kaifa the output of sensor "sensor.kaifa_voltage_l2" is always showing Zero (0)

**Comment by toreamun** [comment]
This is probably because your meter is always sending 0. Some Kaifa meters do this for some elements. See table on page 3 of their specification: https://www.nek.no/wp-content/uploads/2018/11/Kaifa-KFM_001.pdf
