### ISSUE TITLE
Proxy Tibber Pulse MQTT data up to Tibber API?

### ISSUE THREAD

**Issue by sveinse** [toreamun/amshan-homeassistant#64]
When reconfiguring Tibber Pulse to send to a local MQTT server (for HA), the Tibber integration is lost because the data is no longer sent to Tibber. Would it be technically possible to make a MQTT proxy that forwards the Tibber pulse data to the Tibber API? This way it would be possible to keep both the HA integration and the Tibber integration working.

Has anyone looked at what it would take to send the ams MQTT data to the Tibber API? Is there any login and/or certificates we can't access?

**Comment by hansahell** [comment]
Yes, a solution exists already and works great:
https://github.com/MSkjel/LocalPulse2Tibber?fbclid=IwAR0bG_Yur6TxjOajnmlYT02W2DwlbbgAnS3hG-rZ6ItmgSOGpPmYiL6k2L8

**Comment by sveinse** [comment]
Thank you @hansahell . Closing the issue.
