### ISSUE TITLE
Installing gives me the previous version

### ISSUE THREAD

**Issue by jm-cook** [toreamun/amshan-homeassistant#76]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
When I install the latest version using hacs or the wget method I get version 2022.10.2. I expected to get 2023.6.0

## Debug log

```text
{
  "domain": "amshan",
  "name": "AMS HAN meter",
  "version": "2022.10.2",
  "config_flow": true,
  "documentation": "https://github.com/toreamun/amshan-homeassistant",
  "issue_tracker": "https://github.com/toreamun/amshan-homeassistant/issues",
  "codeowners": [
    "@toreamun"
  ],
  "requirements": [
    "amshan[serial]==2.1.1"
  ],
  "after_dependencies": [
    "mqtt"
  ],
  "iot_class": "local_push"
}


```

**Comment by kimma** [comment]
It's just because someone has forgotten to update the manifest with the new version:
https://github.com/toreamun/amshan-homeassistant/blob/2023.6.0/custom_components/amshan/manifest.json

**Comment by toreamun** [comment]
Should be fixed now. Tag 2023.6.0 has been moved one commit forward to get the correct manifest version.
